# Generated by Django 5.1.7 on 2025-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPlantilla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tipo_plantilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoInformix',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('asignado', models.IntegerField()),
                ('suspendido', models.IntegerField()),
                ('reprogramado', models.IntegerField()),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EfectorPlantillaCancelacion',
        ),
        migrations.DeleteModel(
            name='EfectorPlantillaConfirmacion',
        ),
        migrations.DeleteModel(
            name='EfectorPlantillaRecordatorio',
        ),
        migrations.DeleteModel(
            name='EfectorPlantillaReprogramacion',
        ),
    ]
